In [3]:
#1
palabra = input("Ingrese una palabra")
l=list(palabra)
l.reverse()
print(l)

['k', 'f', 'j']


In [7]:
#2
s1=input("Ingrese una cadena")
s2=input("Ingrese una cadena")

l = []
if(len(s1)==len(s2)):
    for i in range(len(s1)):
        l.append(s1[i])
        l.append(s2[i])
    print(l)
else:
    print("Las dos cadenas deben tener la misma longitud")

Las dos cadenas deben tener la misma longitud


In [8]:
#3
s1=input("Ingrese una cadena")
consonantes=[]
vocales=["a","e","i","o","u"]
for i in s1:
    if i not in vocales:
        consonantes.append(i)
print(f"Las consonantes de la cadena {s1}, son: {consonantes}")

Las consonantes de la cadena Felipe, son: ['F', 'l', 'p']


In [13]:
#4
s1=input("Ingrese una cadena")
l=list(s1)
l.reverse()
if l == list(s1):
    print(f"La palabra {s1} es un palídromo")
else:
    print(f"La palabra {s1} no es un palíndromo")
#s1=list(s1)
#print(f"Original:{s1}\nInvertida:{s1_r}")

La palabra ojotojo es un palídromo


In [20]:
#5
import numpy as np
A=np.empty((3,3))
for i in range(len(A)):
    for j in range(len(A)):
        A[i,j]=float(input(f"Ingresa el valor ({i},{j})"))
for columna in A:
    print(max(columna))



2.0
2.0
8.0


In [24]:
#6
n = int(input("Ingrese las dimensiones de la matriz cuadrada"))
A=np.empty((n,n))
contador = 0
for i in range(n):
    for j in range(n):
        A[i,j]=contador
        contador+=1
print(A)
    

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]]


In [42]:
#7
n = int(input("Ingrese n"))
m = int(input("Ingrese m"))
A=np.empty((n,m))
sumas=[]
for i in range(n):
    for j in range(m):
        A[i,j]=float(input(f"Ingresa el valor ({i},{j})"))
        
for j in range(m):
    suma=0
    for i in range(n):
       suma+=A[i,j]
    sumas.append(suma)
if(len(np.unique(sumas))==1):
    print("Todas las columnas suman lo mismo")
else:
    print("Las columnas suman diferente")
print(A)

Las columnas suman diferente
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [47]:
#8
n = int(input("Ingrese n"))
m = int(input("Ingrese m"))
A=np.empty((n,m))
sumas=[]
identidad=True
if n!=m:
     identidad=False
for i in range(n):
    for j in range(m):
        A[i,j]=float(input(f"Ingresa el valor ({i},{j})"))
        if not(i==j and A[i,j]==1 or i!=j and A[i,j]==0):
            identidad=False
            
if(identidad):
    print(f"Matriz identidad\n{A}")
else:
    print(f"La matriz ingresada no es identidad\n{A}")


Matriz identidad
[[1. 0.]
 [0. 1.]]


In [49]:
#9
n = int(input("Ingrese n"))
m = int(input("Ingrese m"))
A=np.empty((n,m))
sumas=[]
identidad=True
B=np.empty((m,n))
for i in range(n):
    for j in range(m):
        A[i,j]=float(input(f"Ingresa el valor ({i},{j})"))
        B[j,i]=A[i,j]
print(f"A:{A}\nA transpuesta:{B}")

A:[[1. 2. 3.]
 [4. 5. 6.]]
A transpuesta:[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [51]:
#10
n = int(input("Ingrese las dimensiones de la matriz identidad"))
A=np.empty((n,n))
contador = 0
for i in range(n):
    for j in range(n):
        if(i==j):
            A[i,j]=1
        elif(i!=j):
            A[i,j]=0
            
print(A)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

In [52]:
l = [0, 1, 2, 3, 2, 1, 0]
for i in l:
    print(i, end = " ")

0 1 2 3 2 1 0 