In [2]:
l = ["Juan",31,172.32,True]
print(l)

['Juan', 31, 172.32, True]


In [3]:
names = ["Maria", "Juan", "Claudia"]

In [4]:
names.insert(1,"Andrés")

In [8]:
for i in names:
    print(i)

Maria
Andrés
Juan
Cristian
Claudia


In [9]:
#Vector con 20 ceros
l=[0]*20
l

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [12]:
#Métodos de listas
numbers = [0,1,1,2,2,2,3,3,3,3]

In [16]:
counted = []
for element in numbers:
    if element not in counted:
        counted.append(element)
        print(f"El elemento {element} aparece {numbers.count(element)}  veces")

El elemento 0 aparece 1  veces
El elemento 1 aparece 2  veces
El elemento 2 aparece 3  veces
El elemento 3 aparece 4  veces


In [19]:
numbers = [1,2,3,4,5]
numbers.extend([6])
print(numbers)
numbers.extend(range(6,19))
print(numbers)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


In [25]:
numbers.pop(6)


6

In [31]:
numbers.reverse()

In [34]:
import random

In [35]:
random.shuffle(numbers)

In [36]:
numbers

[5, 7, 6, 18, 2, 1, 9, 15, 13, 14, 12, 10, 16, 6, 4, 17, 11, 3, 8]

In [37]:
numbers.sort(reverse=True)

In [38]:
numbers

[18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 6, 5, 4, 3, 2, 1]

In [39]:
l=["m","a","r","j","b","g","i","s","f"]

In [40]:
print(f"Lista original: {l}")

Lista original: ['m', 'a', 'r', 'j', 'b', 'g', 'i', 's', 'f']


In [41]:
c= input("Elemento que quieres eliminar")
if c in l:
    l.remove(c)
    print(f"La lista quedó así: {l}")

La lista quedó así: ['m', 'a', 'j', 'b', 'g', 'i', 's', 'f']


In [43]:
reversed = bool(input("Si quieres orden descendente escribe True. De lo contrario ingresa enter"))
l=[]
for i in range(10):
    l.append(float(input()))
l.sort(reverse=reversed)

print(l)

[-3.0, -2.0, -1.0, 0.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


In [44]:
odd=list(range(1,30,2))

In [47]:
for i in range(len(odd)):
    print(f"El valor {odd[i]} ocupa la posición {i}")

El valor 1 ocupa la posición 0
El valor 3 ocupa la posición 1
El valor 5 ocupa la posición 2
El valor 7 ocupa la posición 3
El valor 9 ocupa la posición 4
El valor 11 ocupa la posición 5
El valor 13 ocupa la posición 6
El valor 15 ocupa la posición 7
El valor 17 ocupa la posición 8
El valor 19 ocupa la posición 9
El valor 21 ocupa la posición 10
El valor 23 ocupa la posición 11
El valor 25 ocupa la posición 12
El valor 27 ocupa la posición 13
El valor 29 ocupa la posición 14


In [48]:
#Listas anidadas
l_anidada = [["A","B","C"],[[list(range(10,20,2))],[list(range(5))],[list(range(100,1000,200))]],3]

In [49]:
l_anidada

[['A', 'B', 'C'],
 [[[10, 12, 14, 16, 18]], [[0, 1, 2, 3, 4]], [[100, 300, 500, 700, 900]]],
 3]

In [56]:
l_anidada[1][1][0][2]

2

Matrices

In [57]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [60]:
matrix[2][0]

7

In [61]:
for row in matrix:
    print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [62]:
for row in matrix:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9


In [63]:
m=len(matrix)#filas
n = len(matrix[0])#columnas

for i in range(m):
    for j in range(n):
        print(matrix[i][j],end=" ")
    print("")

1 2 3 
4 5 6 
7 8 9 


In [64]:
for i in matrix:
    for j in i:
        print(j,end=" ")
    print("")

1 2 3 
4 5 6 
7 8 9 


In [67]:
A = [[1,0,-3],[2,0,1],[-1,-1,0]]
B = [[-1,-2,0],[-2,3,0],[0,0,-3]]

m=len(A)
n=len(A[0])

if len(A) == len(B) and len(A[0])==len(B[0]):
    C=[]
    for i in range(m):
        C.append([])
        for j in range(n):
            C[i].append(A[i][j]+B[i][j])
    print(C)
    
else:
    print("No se puede realizar la suma")

[[0, -2, -3], [0, 3, 1], [-1, -1, -3]]


In [69]:
A = [[1,0,-3,2],[2,0,1,1],[-1,0,-1,0]]
B = [[-1,-2,0],[-2,3,0],[0,0,-3],[1,1,-1]]

m,n,p=len(A),len(B),len(B[0])

C=[]

for i in range(m):
    C.append([])
    for j in range(p):
        elemento=0
        for k in range(n):
            elemento = elemento + A[i][k]*B[k][j]
        C[i].append(elemento)

In [74]:
#Matriz 4x4 manualmente

A=[]
for i in range(4):
    A.append([])
    for j in range(4):
        A[i].append(float(input(f"Introduce el elemento ({i},{j})")))
        
        
for i in range(len(A)):
    for i in range(len(A[0])):
        print(A[i][j], end = "  " if A[i][j]>=0 else " ")
    print("")

3.0  7.0  3.0  54.0  
3.0  7.0  3.0  54.0  
3.0  7.0  3.0  54.0  
3.0  7.0  3.0  54.0  


In [77]:
n = int(input("Ingrese el número de filas de las matrices"))
m = int(input("Ingrese el número de columnas de las matrices"))

A=[]

print("\n=== Matriz A ===")

for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input(f"Introduce el elemento ({i},{j})")))
        
B=[]

print("\n=== Matriz B ===")

for i in range(n):
    B.append([])
    for j in range(m):
        B[i].append(float(input(f"Introduce el elemento ({i},{j})")))
        
C=[]

for i in range (n):
    C.append([])
    for j in range(m):
        C[i].append(A[i][j]+B[i][j])
        
print("\n=== Matriz A+B ===")

for i in range(n):
    for j in range(m):
        print(C[i][j], end = " " if C[i][j]>=0 else " ")


=== Matriz A ===

=== Matriz B ===

=== Matriz A+B ===
65.0 6.0 8.0 10.0 

In [80]:
#Producto de dos matrices dadas por el usuario

n = int(input("Numero de filas de A"))
m = int(input("numero de columnas de A"))
p = int(input("numero de columnas de B"))

A = []

print("\n ===Matriz A===")

for i in range(n):
    A.append([])
    for j in range(m):
        A[i].append(float(input(f"Introduce el elemento ({i},{j})")))

B = []

print("\n ===Matriz B===")

for i in range(m):
    B.append([])
    for j in range(p):
        B[i].append(float(input(f"Introduce el elemento ({i},{j})")))

C=[]

for i in range(n):#Filas de A
    C.append([])
    for j in range(p):#Columnas de B    
        elemento = 0
        for k in range(m):#Columnas de A = Filas de B
             elemento += A[i][k] + B[k][j]
        C[i].append(elemento)
print("\n === Matriz A*B ====")
for i in range(n):
    for j in range(p):
        print(C[i][j], end = "  " if C[i][j]>=0 else " ")
    print(" ")


 ===Matriz A===

 ===Matriz B===

 === Matriz A*B ====
3.0  4.0   
3.0  4.0   


In [81]:
import numpy as np

In [82]:
#matriz vacía
A = np.empty((2,3))# 2 filas y 3 columnas

In [83]:
B=np.empty_like(A)#lasa mismas filas y columnas que A

In [85]:
C=np.zeros((3,5))

In [86]:
D=np.zeros_like(A)

In [88]:
E = np.ones((1,4))

In [89]:
F=np.ones_like(C)

In [91]:
M= np.matrix([[1,0,-2,2],[2,0,1,1],[-1,0,-1,0]])

In [95]:
A = np.matrix([[1,0,-3],[2,0,1],[-1,-1,0]])
B = np.matrix([[-1,-2,0],[-2,3,0],[0,0,-3]])

matrixSum=A+B
matrixSum


matrix([[ 0, -2, -3],
        [ 0,  3,  1],
        [-1, -1, -3]])

In [94]:
A = np.matrix([[1,0,-3,2],[2,0,1,1],[-1,0,-1,0]])
B = np.matrix([[-1,-2,0],[-2,3,0],[0,0,-3],[1,1,-1]])
matrixProd=A.dot(B)
matrixProd

matrix([[ 1,  0,  7],
        [-1, -3, -4],
        [ 1,  2,  3]])

In [97]:
n = int(input("Filas de la matriz"))
m = int(input("Columnas de la matriz"))

A = np.empty((n,m))

for i in range(n):
    for j in range(m):
        A[i,j]=float((input(f"Introduce el elemento ({i},{j})")))
print("\n ===Matriz A===")
print(A)


 ===Matriz A===
[[ 1.  0.]
 [ 0.  2.]
 [ 1. -1.]]


In [98]:
n = int(input("Filas de las matrices"))
m = int(input("Columnas de las matrices"))

A=np.empty((n,m))
print("\n ===Matriz A===")
for i in range(n):
    for j in range(m):
        A[i,j]=float((input(f"Introduce el elemento ({i},{j})")))
B=np.empty((n,m))
print("\n ===Matriz B===")
for i in range(n):
    for j in range(m):
        B[i,j]=float((input(f"Introduce el elemento ({i},{j})")))
print("\n === Matriz A + B ===")
print(A+B)


 ===Matriz A===

 ===Matriz B===

 === Matriz A + B ===
[[10.  8.]
 [ 7.  4.]
 [ 4.  1.]
 [ 1.  3.]]


In [99]:
n = int(input("Filas de la matriz A"))
m = int(input("Columnas de la matriz A"))
p = int(input("Columnas de la matrice B"))

A=np.empty((n,m))
print("\n ===Matriz A===")
for i in range(n):
    for j in range (m):
        A[i,j] = float(input(f"Ingrese el elemento ({i},{j})"))
B=np.empty((m,p))
print("\n ===Matriz B===")
for i in range(m):
    for j in range(p):
        B[i,j]=float(input(f"Ingrese el elemento ({i},{j})"))
print("A*B")
print(A.dot(B))


 ===Matriz A===

 ===Matriz B===
A*B
[[ 3.  2.  0.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
